### ISSUE TITLE
wiki page

### ISSUE THREAD

**Issue by ricardotaborda** [GPSR2017/GPS_R#5]
something is wrong with the wiki link in the github page of the project. I thought you had already created a wiki for the original one. did you forgot to port it to the new project repo? please check.

**Comment by pomath** [comment]
looks like it didn't transfer, oops!  I'll remake it.

**Comment by ricardotaborda** [comment]
I see the wiki is now active but pretty much empty. Please start working on populating this. The first step is to give a very general description of what is the software about, and then start to grow from there with documentation intended for users, not programmers.

**Comment by cbaker415** [comment]
An extremely general description has been updated. Will be refined later on. Also the intent to add pictures has been added, but the pictures have not yet been captured to add all on my local fork.

 How do you pull a wiki from a fork to the main program?

**Comment by ricardotaborda** [comment]
The wiki should not be created in a fork, because it does not work the same way as the repository. So the wiki in a fork is not naturally linked to the wiki in the main project. Instead, create the wiki directly in the main project website and forget about the wiki of the fork. If you already created it in a fork, then clone it locally, then push it to the remote of the main project.

For the question about images in the wiki, please remind me to explain this in class on Thursday because it is not as straight forward as I explained the first time.

**Comment by cbaker415** [comment]
I do not have access to edit the wiki page on the main repository. It returns:

coltonbaker GPS_R.wiki\ $ git push
remote: Permission to GPSR2017/GPS_R.wiki.git denied to cbaker415.
fatal: unable to access 'https://github.com/GPSR2017/GPS_R.wiki.git/': The requested URL returned error: 403

Peter can you add me so that I can push the changes that I made on my local repository.

**Comment by pomath** [comment]
Okay added you as a collaborator, if it still doesn't work, try editing it on the web page.

**Comment by cbaker415** [comment]
That worked. Thanks
